9.27: pyyaml issues may caused by python 3.8